#!/usr/bin/bash

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
build_path="${script_dir}/../build"

cmake -DCMAKE_BUILD_TYPE=Release ${script_dir}

if [ -d "${build_path}" ]
then
    cmake -B ${build_path}
    cmake --build ${build_path} --target clean; 
else
    mkdir ${build_path}
    cmake -B ${build_path}
fi

cmake --build ${build_path} -j$(nproc) || exit 1

#echo "Run application: (y/n)?"
#read answer
#if [ "${answer}" = "y" ]
#then
    "${build_path}/ImageDownloader"
#fi